services:
  - type: web
    name: overcomers-sle
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: "3.12.7"
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: SESSION_COOKIE_SECURE
        value: "1"
